steps:
  # Cloud Functions 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - content-factory
      - --gen2
      - --runtime=nodejs20
      - --region=asia-northeast3
      - --source=functions
      - --entry-point=main
      - --trigger-http
      - --allow-unauthenticated
      - --max-instances=100
      - --memory=512MB
      - --timeout=300s
    timeout: 600s

options:
  logging: CLOUD_LOGGING_ONLY
